# Generated by Django 4.2.3 on 2023-07-10 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('govern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='name',
            field=models.TextField(null=True),
        ),
    ]
